name: gopaperboy
favicon: null
layout_spectrum: 0.8206999264657497
typography_spectrum: 0.7148480908945203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ef6a4f'
    - '#231f20'
    - '#537698'
    - '#ffffff'
    - '#ff0000'
  brandStrength: 0.5686697559431195
  lightness: 0.40665021748282015
  saturation: 0.8142282636836171
  rhythmicContrast: 0.4329688309226185
purpose: []
